# the path to the HoloLens camera
VIDEO_SOURCE: https://jspirig:janspi10@192.168.43.54/api/holographic/stream/live.mp4?olo=true&pv=true&mic=true&loopback=true
# for testing it is maybe easier to use the webcam to detect some objects
USE_WEBCAM: True
# if we want t©o do object recognition
RUN_INFERENCE: True
# if we want to use tiny version of yolo which achieves around 30 frames per second on CPU
USE_YOLO-TINY: True
# the minimum confidence level to say it is a valid detection
MIN_CONFIDENCE_LEVEL: 0.3
# if we want to show the output or not
SHOW_OUTPUT: True
# Path were the output video should be saved (as .avi)
RESULT_PATH: "/Users/janickspirig/Desktop/results.avi"